[package]
name = "rust_bitcoin_node"
version = "0.1.0"
authors = ["Jake Rawsthorne <jake@jakerawsthorne.co.uk>"]
edition = "2018"

[dependencies]
# tokio = { git = "https://github.com/tokio-rs/tokio", features=["full"] }
# tokio-util = { version = "0.3.1", features=["codec"] }
bitcoin = { git="https://github.com/jrawsthorne/rust-bitcoin", features=["bitcoinconsensus", "rand"] }
# bitcoin = { path="../rust-bitcoin", features=["bitcoinconsensus", "rand"] }
log = "0.4"
env_logger = "0.7"
# bytes = "0.5"
# futures = "0.3"
# futures-util = "0.3"
# failure = "0.1"
rocksdb = "0.13"
# async-trait = "0.1"
bitcoinconsensus = "0.19.0-1 "
regex = "1"
# chrono = "0.4"
bitflags = "1"
# num_cpus = "1.13"
maplit = "1.0.2"
parking_lot = "0.10"
rayon = "1.3.0"
thiserror = "1.0"
murmur3 = "0.5.1"

[dev-dependencies]
tempfile = "3"