[package]
name = "rust_bitcoin_node"
version = "0.1.0"
authors = ["Jake Rawsthorne <jake@jakerawsthorne.co.uk>"]
edition = "2018"

[dependencies]
tokio = { version = "0.2", features=["full"] }
tokio-util = { version = "0.2", features=["codec"] }
bitcoin = { git="https://github.com/rust-bitcoin/rust-bitcoin", features=["bitcoinconsensus","rand"] }
log = "0.4"
env_logger = "0.7"
bytes = "0.5"
futures = "0.3"
futures-util = "0.3"
failure = "0.1"
rocksdb = "0.13"
async-trait = "0.1"
bitcoinconsensus = "0.19.0-1 "
regex = "1"
chrono = "0.4"
bitflags = "1"
num_cpus = "1.12"

[dev-dependencies]
tempfile = "3"