[package]
name = "rust_bitcoin_node"
version = "0.1.0"
authors = ["Jake Rawsthorne <jake@jakerawsthorne.co.uk>"]
edition = "2018"

[dependencies]
bitcoin = { git="https://github.com/jrawsthorne/rust-bitcoin", features=["bitcoinconsensus", "rand"] }
log = "0.4"
env_logger = "0.7"
bytes = "0.5"
rocksdb = "0.15"
bitcoinconsensus = "0.19.0-1 "
regex = "1"
bitflags = "1"
maplit = "1.0.2"
parking_lot = "0.11"
rayon = "1.4"
thiserror = "1.0"
murmur3 = "0.5.1"
bitcoin-wallet = { git="https://github.com/jrawsthorne/rust-wallet" }
crossbeam-channel = "0.4"

[dev-dependencies]
tempfile = "3"