[package]
name = "rust-bitcoin-node"
version = "0.1.0"
authors = ["Jake Rawsthorne <jake@jakerawsthorne.co.uk>"]
edition = "2018"

[dependencies]
tokio = { version = "0.2", features=["full"] }
# tokio-util = { version = "0.2", features=["codec"] }
# rand = "0.7"
bitcoin = { git="https://github.com/rust-bitcoin/rust-bitcoin", features=["bitcoinconsensus"] }
log = "0.4"
env_logger = "0.7"
# bytes = "0.5"
# futures = "0.3"
# futures-util = "0.3"
failure = "0.1"
rocksdb = "0.13"
# lru = "0.4"